export const lang = {
    home: {
        header_jr: 'Today',
        header_zp: 'Early Market',
        header_gq: 'Live',
        header_cg: 'COMBO',
        header_wdtz: 'MY BETS',
        header_zm: 'STATEMENTS',
        header_ssjg: 'RESULTS',
        header_gzytk: 'RULES AND PROVISIONS',
        bar_msg: 'notice',
        bar_select: 'select',
        bar_px: 'Sort',
        bar_ptpx: 'normal',
        bar_sjpx: 'time',
        bar_rqpx: 'Time Sort',
        bar_kyzj: 'Available Balance',
        bar_ewm: 'QR CODE',
        table_sj: 'TIME',
        table_ss: 'EVENT',
        table_sfp: '1X2',
        table_rq: 'HDP',
        table_dx: 'OU',
        table_msg: 'No event',
        table_show: 'show',
        table_hide: 'hide',
        table_score: 'No live scores ',
        pageView_video: 'live video',
        pageView_score: 'live score',
        pageView_dz: 'SINGLE',
        pageView_cg: 'COMBO',
        pageView_nVideo: 'No live video',
        pageView_tzd: 'Betting slips',
        pageView_bztzd: 'Standard order',
        pageView_sx: 'Refresh',
        pageView_bj: 'Principal',
        pageView_rule: 'Accept Better Odds',
        pageView_pcje: 'Max Payout',
        pageView_zdtz: 'Min',
        pageView_zgtz: 'Max',
        pageView_yxzs: 'Selected',
        pageView_qk: 'Empty',
        pageView_qr: 'Confirm',
        pageView_qx: 'Cancel',
        pageView_xgpl: 'Hong Kong odds',
        pageView_djpl: 'Click on the odds to add options',
        pageView_dqszd: 'Clearing note',
        pageView_ky: 'Can win',
        pageView_tzje: 'Bet amount',
        pageView_jxz: 'underway',
        pageView_ckgd: 'See more',
        bet_tzxe: 'Please note the betting limit',
        bet_xzcg: 'Betting on success',
    },
    betRecord: {
        from_status: 'State',
        from_yjs: 'CLSD',
        from_wjs: 'Accountopen',
        from_xzsj:'Select time',
        from_cx: 'Submit',
        table_xzsj: 'Bet time',
        table_detailed_info: 'Detailed info',
        table_odds: 'Odds',
        table_txje: 'Bet amount',
        table_sy: 'Win_Los',
        table_zt: 'Status',
        table_dzjj: 'e-sports',
        table_xgpl: 'HK-Odds',
        table_ozpl: 'European Odds',
        table_y: 'Win',
        table_s: 'Loss',
        table_xj: 'Subtotal',
        table_zj: 'Aggregate',
        table_zwsj: 'No Data',
        table_qzy: 'Please Note',
        table_gjsq: 'According to the time zone',
        table_jdrq: 'decided to date',
        table_sjfw: 'The date range cannot exceed 30 days'
    },
    announcement:{
        from_zx_info: 'News',
        from_start: 'Start time',
        from_end: 'End time',
        from_bh: 'Number',
        from_date: 'Date',
        from_info: 'Info'
    },
    results: {
        from_date: 'Date',
        from_xzls: 'select league',
        from_cx: 'Submit',
        table_event: 'event',
        table_zwsg: 'No data'
    },
    statements: {
        from_time: 'Select time',
        from_sub: 'Submit',
        from_cxlsjl: 'Query history',
        from_back: 'Back',
        header_note: 'Please note',
        header_text: 'Wallet refers to sports betting. You can check the data report of any month in the last year and a half',
        table_date: 'Date',
        table_bz: 'Remark',
        table_jye: 'Sum',
        table_zcsr: 'Expend/Income',
        table_ye: 'Balance',
        table_cz: 'Operate',
        table_zwjl: 'No data',
        table_xh: 'NO',
        table_jysj: 'Trading Hours',
        table_xzxq: 'Bet on details',
        table_pl: 'Odds',
        table_xzje: 'Bet amount',
        table_sy: 'Win_Los',
        table_status: 'Status',
        table_HKD: 'HK-Dish',
        OT: '1x2',
        hdp: 'HDP',
        ou: 'OU'
    },
}