export const lang = {
    home: {
        header_jr: 'Today',
        header_zp: 'Early Market',
        header_gq: 'Live',
        header_wdtz: 'bet statistics',
        header_zm: 'accounts',
        header_ssjg: 'Match Results',
        header_gzytk: 'Rules and provisions',
        bar_msg: 'notice',
        bar_select: 'select',
        bar_kyzj: 'Available capital',
        table_sj: 'time',
        table_ss: 'events',
        table_sfp: '1X2',
        table_rq: 'HDP',
        table_dx: 'OU',
        table_msg: 'No event',
        table_show: 'show',
        table_hide: 'hide',
        table_score: 'No live scores ',
        pageView_video: 'live video',
        pageView_score: 'live score',
        pageView_nVideo: 'No live video',
        pageView_tzd: 'Betting slips',
        pageView_bztzd: 'Standard order',
        pageView_sx: 'Refresh',
        pageView_bj: 'Principal',
        pageView_rule: 'Accept the latest odds',
        pageView_pcje: 'winning result',
        pageView_zdtz: 'minimum bet',
        pageView_zgtz: 'BET MAX',
        pageView_qr: 'Confirm',
        pageView_qx: 'Cancel',
        pageView_xgpl: 'Hong Kong odds',
        pageView_djpl: 'Click on the odds to add options',
        pageView_dqszd: 'Clearing note',
        pageView_ky: 'Can win',
        pageView_tzje: 'Bet amount',
        pageView_jxz: 'underway',
        pageView_ckgd: 'See more',
        bet_tzxe: 'Please note the betting limit',
        bet_xzcg: 'Betting on success',
    },
    betRecord: {
        from_status: 'State',
        from_yjs: 'CLSD',
        from_wjs: 'accountopen'
    }
}